test:
  image: node:11
  before_script:
    - yarn config set cache-folder "$(pwd)/.yarn"
    - yarn install
  script:
    - yarn build
    - yarn lint
    - yarn test
    - yarn markdownlint
    # Make sure build output has been committed.
    - git status --porcelain || (echo "Repo is dirty"; git diff; false)
  cache:
    paths:
      - node_modules
      - .yarn
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    reports:
      junit: junit-*.xml
    paths:
      - coverage
