test:
  image: node:11
  before_script:
    - npm config set cache "$(pwd)/.npm"
    - npm install
  script:
    - npm run build
    - npm run lint
    - npm run test
    - npm run markdownlint
    # Make sure build output has been committed.
    - git status --porcelain || (echo "Repo is dirty"; git diff; false)
  cache:
    paths:
      - node_modules
      - .npm
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    reports:
      junit: junit-*.xml
    paths:
      - coverage
